name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: cd auth && docker build -t birdglove2/auth .
      - name: Login user to docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker
        run: docker push birdglove2/auth
      - name: Connect digitalocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save kubernetes to the digitalocean cluster
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: Restart Deployment
        run: kubectl rollout restart deployment auth-depl
