name: tests-order

on:
  pull_request:
    path:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd order && npm install && npm run test:ci
