name: tests

on: 
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Mongo
        run:  sudo docker run --name mongo -d -p 27017:27017 mongo
      - name: Run each service test
        run: cd auth && npm install && npm run test:ci
        env:
          CI: true
      
      
